version: '3'
services:
  frontend:
    build: ./frontend
    ports:
      - "4200:4200"
    volumes:
      - ./frontend/:/app
    networks:
      - doranco-network

  backend:
    build: ./backend
    volumes:
      - ./backend/:/app
    networks:
      - doranco-network

networks:
  doranco-network:
    driver: bridge
